### ISSUE TITLE
this script doesn't work for me (new firmware version)

### ISSUE THREAD

**Issue by llo94** [mkubicek/tpylink#1]
Hello,
I didn't get to understand why but the **tpylink** python script does not work on my TL WR841N router with the following configuration:
```
Firmware Version: | 3.16.9 Build 170210 Rel.42078n
Hardware Version: | WR841N v8 00000000
```

The error message is : 
```
Login error. No authentification key found in response.
<body><script language="javaScript">window.parent.location.href = "http://192.168.1.253";
</script></body></html>
```

Is there a way to make it work ? or should I forget it ?

Thanks
Regards

Laurent

**Comment by mkubicek** [comment]
Hi Laurent

Unfortunately I don't own a TP-Link router anymore so I can't test it.

I assume you're running the script with the correct username/password and ip of your router. Can you check using your browsers developer tools whether the login response still looks the same? There should be an authentication token in the response (see line 46 in the script)

Cheers,
m

**Comment by maesoser** [comment]
Hi @llo94 ¿Are you still facing issues? I found this script, I converted from python2 to python3 using `2to3` and I also had some problems making it work, but I am not sure if it was just my internet connection.

@mkubicek , I think you can close this issue, if you want. I made a [prometheus exporter](https://github.com/maesoser/tplink_exporter) thanks t your code by the way.

Have a good day!
