### ISSUE TITLE
Not accepting attributes -h -u -p

### ISSUE THREAD

**Issue by bojan385** [mkubicek/tpylink#2]
There is something wrong with the script when reading aditional attributes.
for example:

python tpylink.py -h 192.168.100.2 -u admin -p admin1234 -t
does not work.

But it works when I change line 28 in script to:
def __init__(self, host="192.168.100.2", username="admin", password="admin1234"):

Interestingly, attributes -t and -r work OK.

**Comment by mkubicek** [comment]
Sorry for the late reply. Can't reproduce the issue, please provide details if you still need this script!
